# main menu
[[main]]
name = "Etusivu"
url = "/"
weight = 1

[[main]]
name = "Liittymät"
weight = 2
hasChildren = true

#  [[main]]
#  parent = "Liittymät"
#  name = "Kaikki liittymät"
#  url = "liittymat"
#  weight = 1

  [[main]]
  parent = "Liittymät"
  name = "Puhelinliittymät"
  url = "liittymat/puhelin"
  weight = 2

  [[main]]
  parent = "Liittymät"
  name = "Netti kotiin ja mukaan"
  url = "liittymat/netti"
  weight = 3

  [[main]]
  parent = "Liittymät"
  name = "Uudet liittymät"
  url = "liittymat/uusi-liittyma"
  weight = 4

[[main]]
name = "Blogi"
url = "blogi"
weight = 3

[[main]]
name = "Meistä"
url = "ukk"
weight = 4

# footer menu left
[[footer_left]]
name = "Meistä"
url = "/ukk"
weight = 1

# footer menu left
[[footer_left]]
name = "Blogi"
url = "/blogi"
weight = 2

# footer menu middle
[[footer_middle]]
name = "Puhelinliittymät"
url = "/liittymat/puhelin"
weight = 1

[[footer_middle]]
name = "Netti kotiin tai mukaan"
url = "/liittymat/netti"
weight = 2

[[footer_middle]]
name = "Uusi liittymä"
url = "/liittymat/uusi-liittyma"
weight = 3

# footer menu right
[[footer_right]]
name = "Ota yhteyttä"
url = "/ota-yhteytta"
weight = 1

#[[footer_right]]
#name = "Käyttöehdot"
#url = "/ehdot"
#weight = 2

# footer menu right
[[footer_right]]
name = "Tietosuoja"
url = "/tietosuoja"
weight = 3