# main menu
[[main]]
name = "Etusivu"
url = "/"
weight = 1

[[main]]
name = "Tarjoukset"
url = "tarjoukset"
weight = 2
hasChildren = true

  [[main]]
  parent = "Tarjoukset"
  name = "Kaikki tarjoukset"
  url = "tarjoukset"
  weight = 1

  [[main]]
  parent = "Tarjoukset"
  name = "Puhelinliittymät"
  url = "tarjoukset/puhelin"
  weight = 2

  [[main]]
  parent = "Tarjoukset"
  name = "Netti kotiin ja mukaan"
  url = "tarjoukset/netti"
  weight = 3

  [[main]]
  parent = "Tarjoukset"
  name = "Uudet liittymät"
  url = "tarjoukset/uudet-liittymat"
  weight = 4

[[main]]
name = "Blogi"
url = "blogi"
weight = 3

[[main]]
name = "UKK"
url = "ukk"
weight = 4

# footer menu left
[[footer_left]]
name = "Meistä"
url = "#"

#[[footer_left]]
#name = "Quick Start"
#url = "#"

#[[footer_left]]
#name = "Pricing"
#url = "pricing"

# footer menu middle
[[footer_middle]]
name = "Puheliittymät"
url = "/deals/sub_mob"

[[footer_middle]]
name = "Laajakaistat"
url = "/deals/sub_mob"

[[footer_middle]]
name = "Uudet liittymät"
url = "/deals/sub_new"

# footer menu right
[[footer_right]]
name = "Privacy Policy"
url = "privacy-policy"

[[footer_right]]
name = "Terms & Conditions"
url = "terms-conditions"

[[footer_right]]
name = "UKK"
url = "faq"